import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components/sections";
import SmoothScroll from "@/components/ui/SmoothScroll";
import { GoogleAnalytics } from '@next/third-parties/google'


const poppins = Poppins({
  weight: ["400","600","900"],
  subsets:["latin"]
})


export const metadata: Metadata = {
  title: "Muffer - Get Creative Instantly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`+ ""}
      >
        <Navbar/>
        <SmoothScroll>
        {children}
        </SmoothScroll>
        <Footer/>
        <GoogleAnalytics gaId="G-XYZ" />
      </body>
    </html>
  );
}
